[build-system]
requires = ["setuptools>=77", "setuptools_scm>=8"]
build-backend = "setuptools.build_meta"

[project]
name = "jax-pme"
description = "(Particle Mesh) Ewald summation in JAX"
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [{ name = "Marcel Langer", email = "dev@marcel.science" }]
requires-python = ">=3.10"
dependencies = [
    "jax>=0.4.30",
    "vesin>=0.4.0",
    "ase>=3.22.1",
    "numpy",
]
dynamic = ["version"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering :: Chemistry",
    "Topic :: Scientific/Engineering :: Physics",
]

[project.optional-dependencies]
dev = ["pytest", "ruff"]

[project.urls]
Homepage = "https://github.com/lab-cosmo/jax-pme"
Repository = "https://github.com/lab-cosmo/jax-pme"
Issues = "https://github.com/lab-cosmo/jax-pme/issues"

[tool.setuptools_scm]
version_file = "jaxpme/_version.py"

[tool.setuptools.packages.find]
include = ["jaxpme*"]

[tool.ruff]
line-length = 92
exclude = ["jaxpme/_version.py"]

[tool.ruff.lint]
select = [
    # pycodestyle
    "E",
    # Pyflakes
    "F",
    # pyupgrade
    "UP",
    # isort
    "I",
]
# E741: don't worry about short variable names
# E731: don't worry about lambdas
ignore = ["E741", "E731"]

[tool.ruff.lint.isort]
section-order = ["numpy", "jax", "future", "standard-library", "third-party", "first-party", "local-folder"]
no-lines-before = ["jax"]

[tool.ruff.lint.isort.sections]
"numpy" = ["numpy"]
"jax" = ["jax", "jax.numpy"]
